// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: banner.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int64                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *Banner) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Banner) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Banner) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_banner_proto protoreflect.FileDescriptor

const file_banner_proto_rawDesc = "" +
	"\n" +
	"\fbanner.proto\x12\x02pb\"q\n" +
	"\x06Banner\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x03R\bbannerId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_banner_proto_rawDescOnce sync.Once
	file_banner_proto_rawDescData []byte
)

func file_banner_proto_rawDescGZIP() []byte {
	file_banner_proto_rawDescOnce.Do(func() {
		file_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banner_proto_rawDesc), len(file_banner_proto_rawDesc)))
	})
	return file_banner_proto_rawDescData
}

var file_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_banner_proto_goTypes = []any{
	(*Banner)(nil), // 0: pb.Banner
}
var file_banner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_banner_proto_init() }
func file_banner_proto_init() {
	if File_banner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banner_proto_rawDesc), len(file_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_banner_proto_goTypes,
		DependencyIndexes: file_banner_proto_depIdxs,
		MessageInfos:      file_banner_proto_msgTypes,
	}.Build()
	File_banner_proto = out.File
	file_banner_proto_goTypes = nil
	file_banner_proto_depIdxs = nil
}
