// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: dish.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dish struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DishId            int64                  `protobuf:"varint,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price             int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	DiscountRate      float32                `protobuf:"fixed32,4,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	DiscountAmount    int32                  `protobuf:"varint,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Description       string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Content           string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Author            string                 `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	ThumbnailUrl      string                 `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	Status            string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Images            []string               `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SalePrice         int32                  `protobuf:"varint,14,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	DiscountExpiredAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=discount_expired_at,json=discountExpiredAt,proto3" json:"discount_expired_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_dish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Dish) GetDiscountRate() float32 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *Dish) GetDiscountAmount() int32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Dish) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Dish) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Dish) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Dish) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Dish) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Dish) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Dish) GetSalePrice() int32 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *Dish) GetDiscountExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscountExpiredAt
	}
	return nil
}

var File_dish_proto protoreflect.FileDescriptor

const file_dish_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dish.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x04\n" +
	"\x04Dish\x12\x17\n" +
	"\adish_id\x18\x01 \x01(\x03R\x06dishId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12#\n" +
	"\rdiscount_rate\x18\x04 \x01(\x02R\fdiscountRate\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x05R\x0ediscountAmount\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\b \x01(\tR\x06author\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\x12B\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vpublishedAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x16\n" +
	"\x06images\x18\f \x03(\tR\x06images\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"sale_price\x18\x0e \x01(\x05R\tsalePrice\x12J\n" +
	"\x13discount_expired_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x11discountExpiredAtB\x0f\n" +
	"\r_published_atB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_dish_proto_rawDescOnce sync.Once
	file_dish_proto_rawDescData []byte
)

func file_dish_proto_rawDescGZIP() []byte {
	file_dish_proto_rawDescOnce.Do(func() {
		file_dish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dish_proto_rawDesc), len(file_dish_proto_rawDesc)))
	})
	return file_dish_proto_rawDescData
}

var file_dish_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dish_proto_goTypes = []any{
	(*Dish)(nil),                  // 0: pb.Dish
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_dish_proto_depIdxs = []int32{
	1, // 0: pb.Dish.published_at:type_name -> google.protobuf.Timestamp
	1, // 1: pb.Dish.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: pb.Dish.discount_expired_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dish_proto_init() }
func file_dish_proto_init() {
	if File_dish_proto != nil {
		return
	}
	file_dish_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dish_proto_rawDesc), len(file_dish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dish_proto_goTypes,
		DependencyIndexes: file_dish_proto_depIdxs,
		MessageInfos:      file_dish_proto_msgTypes,
	}.Build()
	File_dish_proto = out.File
	file_dish_proto_goTypes = nil
	file_dish_proto_depIdxs = nil
}
