// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_add_dish_image.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddDishImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishId        int64                  `protobuf:"varint,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	ImageId       int64                  `protobuf:"varint,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDishImageRequest) Reset() {
	*x = AddDishImageRequest{}
	mi := &file_rpc_add_dish_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDishImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishImageRequest) ProtoMessage() {}

func (x *AddDishImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_dish_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishImageRequest.ProtoReflect.Descriptor instead.
func (*AddDishImageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_dish_image_proto_rawDescGZIP(), []int{0}
}

func (x *AddDishImageRequest) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *AddDishImageRequest) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

type AddDishImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDishImageResponse) Reset() {
	*x = AddDishImageResponse{}
	mi := &file_rpc_add_dish_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDishImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishImageResponse) ProtoMessage() {}

func (x *AddDishImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_dish_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishImageResponse.ProtoReflect.Descriptor instead.
func (*AddDishImageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_dish_image_proto_rawDescGZIP(), []int{1}
}

var File_rpc_add_dish_image_proto protoreflect.FileDescriptor

const file_rpc_add_dish_image_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_add_dish_image.proto\x12\x02pb\"I\n" +
	"\x13AddDishImageRequest\x12\x17\n" +
	"\adish_id\x18\x01 \x01(\x03R\x06dishId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\x03R\aimageId\"\x16\n" +
	"\x14AddDishImageResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_add_dish_image_proto_rawDescOnce sync.Once
	file_rpc_add_dish_image_proto_rawDescData []byte
)

func file_rpc_add_dish_image_proto_rawDescGZIP() []byte {
	file_rpc_add_dish_image_proto_rawDescOnce.Do(func() {
		file_rpc_add_dish_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_add_dish_image_proto_rawDesc), len(file_rpc_add_dish_image_proto_rawDesc)))
	})
	return file_rpc_add_dish_image_proto_rawDescData
}

var file_rpc_add_dish_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_dish_image_proto_goTypes = []any{
	(*AddDishImageRequest)(nil),  // 0: pb.AddDishImageRequest
	(*AddDishImageResponse)(nil), // 1: pb.AddDishImageResponse
}
var file_rpc_add_dish_image_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_add_dish_image_proto_init() }
func file_rpc_add_dish_image_proto_init() {
	if File_rpc_add_dish_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_add_dish_image_proto_rawDesc), len(file_rpc_add_dish_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_dish_image_proto_goTypes,
		DependencyIndexes: file_rpc_add_dish_image_proto_depIdxs,
		MessageInfos:      file_rpc_add_dish_image_proto_msgTypes,
	}.Build()
	File_rpc_add_dish_image_proto = out.File
	file_rpc_add_dish_image_proto_goTypes = nil
	file_rpc_add_dish_image_proto_depIdxs = nil
}
