// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_add_post_to_category.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPostToCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostToCategoryRequest) Reset() {
	*x = AddPostToCategoryRequest{}
	mi := &file_rpc_add_post_to_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostToCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostToCategoryRequest) ProtoMessage() {}

func (x *AddPostToCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_post_to_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostToCategoryRequest.ProtoReflect.Descriptor instead.
func (*AddPostToCategoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_post_to_category_proto_rawDescGZIP(), []int{0}
}

func (x *AddPostToCategoryRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddPostToCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type AddPostToCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostToCategoryResponse) Reset() {
	*x = AddPostToCategoryResponse{}
	mi := &file_rpc_add_post_to_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostToCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostToCategoryResponse) ProtoMessage() {}

func (x *AddPostToCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_post_to_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostToCategoryResponse.ProtoReflect.Descriptor instead.
func (*AddPostToCategoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_post_to_category_proto_rawDescGZIP(), []int{1}
}

var File_rpc_add_post_to_category_proto protoreflect.FileDescriptor

const file_rpc_add_post_to_category_proto_rawDesc = "" +
	"\n" +
	"\x1erpc_add_post_to_category.proto\x12\x02pb\"T\n" +
	"\x18AddPostToCategoryRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\"\x1b\n" +
	"\x19AddPostToCategoryResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_add_post_to_category_proto_rawDescOnce sync.Once
	file_rpc_add_post_to_category_proto_rawDescData []byte
)

func file_rpc_add_post_to_category_proto_rawDescGZIP() []byte {
	file_rpc_add_post_to_category_proto_rawDescOnce.Do(func() {
		file_rpc_add_post_to_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_add_post_to_category_proto_rawDesc), len(file_rpc_add_post_to_category_proto_rawDesc)))
	})
	return file_rpc_add_post_to_category_proto_rawDescData
}

var file_rpc_add_post_to_category_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_post_to_category_proto_goTypes = []any{
	(*AddPostToCategoryRequest)(nil),  // 0: pb.AddPostToCategoryRequest
	(*AddPostToCategoryResponse)(nil), // 1: pb.AddPostToCategoryResponse
}
var file_rpc_add_post_to_category_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_add_post_to_category_proto_init() }
func file_rpc_add_post_to_category_proto_init() {
	if File_rpc_add_post_to_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_add_post_to_category_proto_rawDesc), len(file_rpc_add_post_to_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_post_to_category_proto_goTypes,
		DependencyIndexes: file_rpc_add_post_to_category_proto_depIdxs,
		MessageInfos:      file_rpc_add_post_to_category_proto_msgTypes,
	}.Build()
	File_rpc_add_post_to_category_proto = out.File
	file_rpc_add_post_to_category_proto_goTypes = nil
	file_rpc_add_post_to_category_proto_depIdxs = nil
}
