// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_dishes.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDishesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DishIds         []int64                `protobuf:"varint,1,rep,packed,name=dish_ids,json=dishIds,proto3" json:"dish_ids,omitempty"`
	Search          *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Author          *string                `protobuf:"bytes,3,opt,name=author,proto3,oneof" json:"author,omitempty"`
	PublishedAtFrom *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=published_at_from,json=publishedAtFrom,proto3,oneof" json:"published_at_from,omitempty"`
	PublishedAtTo   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at_to,json=publishedAtTo,proto3,oneof" json:"published_at_to,omitempty"`
	PriceFrom       *int32                 `protobuf:"varint,6,opt,name=price_from,json=priceFrom,proto3,oneof" json:"price_from,omitempty"`
	PriceTo         *int32                 `protobuf:"varint,7,opt,name=price_to,json=priceTo,proto3,oneof" json:"price_to,omitempty"`
	SortBy          *string                `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortDirection   *string                `protobuf:"bytes,9,opt,name=sort_direction,json=sortDirection,proto3,oneof" json:"sort_direction,omitempty"`
	Limit           *int32                 `protobuf:"varint,10,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset          *int32                 `protobuf:"varint,11,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Status          *string                `protobuf:"bytes,12,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDishesRequest) Reset() {
	*x = GetDishesRequest{}
	mi := &file_rpc_get_dishes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesRequest) ProtoMessage() {}

func (x *GetDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_dishes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesRequest.ProtoReflect.Descriptor instead.
func (*GetDishesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_dishes_proto_rawDescGZIP(), []int{0}
}

func (x *GetDishesRequest) GetDishIds() []int64 {
	if x != nil {
		return x.DishIds
	}
	return nil
}

func (x *GetDishesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetDishesRequest) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *GetDishesRequest) GetPublishedAtFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAtFrom
	}
	return nil
}

func (x *GetDishesRequest) GetPublishedAtTo() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAtTo
	}
	return nil
}

func (x *GetDishesRequest) GetPriceFrom() int32 {
	if x != nil && x.PriceFrom != nil {
		return *x.PriceFrom
	}
	return 0
}

func (x *GetDishesRequest) GetPriceTo() int32 {
	if x != nil && x.PriceTo != nil {
		return *x.PriceTo
	}
	return 0
}

func (x *GetDishesRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *GetDishesRequest) GetSortDirection() string {
	if x != nil && x.SortDirection != nil {
		return *x.SortDirection
	}
	return ""
}

func (x *GetDishesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetDishesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetDishesRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetDishesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	TotalCase     int32                  `protobuf:"varint,2,opt,name=total_case,json=totalCase,proto3" json:"total_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesResponse) Reset() {
	*x = GetDishesResponse{}
	mi := &file_rpc_get_dishes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesResponse) ProtoMessage() {}

func (x *GetDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_dishes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesResponse.ProtoReflect.Descriptor instead.
func (*GetDishesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_dishes_proto_rawDescGZIP(), []int{1}
}

func (x *GetDishesResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishesResponse) GetTotalCase() int32 {
	if x != nil {
		return x.TotalCase
	}
	return 0
}

var File_rpc_get_dishes_proto protoreflect.FileDescriptor

const file_rpc_get_dishes_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_get_dishes.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"dish.proto\"\xfb\x04\n" +
	"\x10GetDishesRequest\x12\x19\n" +
	"\bdish_ids\x18\x01 \x03(\x03R\adishIds\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x03 \x01(\tH\x01R\x06author\x88\x01\x01\x12K\n" +
	"\x11published_at_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0fpublishedAtFrom\x88\x01\x01\x12G\n" +
	"\x0fpublished_at_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rpublishedAtTo\x88\x01\x01\x12\"\n" +
	"\n" +
	"price_from\x18\x06 \x01(\x05H\x04R\tpriceFrom\x88\x01\x01\x12\x1e\n" +
	"\bprice_to\x18\a \x01(\x05H\x05R\apriceTo\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\b \x01(\tH\x06R\x06sortBy\x88\x01\x01\x12*\n" +
	"\x0esort_direction\x18\t \x01(\tH\aR\rsortDirection\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\n" +
	" \x01(\x05H\bR\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\v \x01(\x05H\tR\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\f \x01(\tH\n" +
	"R\x06status\x88\x01\x01B\t\n" +
	"\a_searchB\t\n" +
	"\a_authorB\x14\n" +
	"\x12_published_at_fromB\x12\n" +
	"\x10_published_at_toB\r\n" +
	"\v_price_fromB\v\n" +
	"\t_price_toB\n" +
	"\n" +
	"\b_sort_byB\x11\n" +
	"\x0f_sort_directionB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_status\"T\n" +
	"\x11GetDishesResponse\x12 \n" +
	"\x06dishes\x18\x01 \x03(\v2\b.pb.DishR\x06dishes\x12\x1d\n" +
	"\n" +
	"total_case\x18\x02 \x01(\x05R\ttotalCaseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_dishes_proto_rawDescOnce sync.Once
	file_rpc_get_dishes_proto_rawDescData []byte
)

func file_rpc_get_dishes_proto_rawDescGZIP() []byte {
	file_rpc_get_dishes_proto_rawDescOnce.Do(func() {
		file_rpc_get_dishes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_dishes_proto_rawDesc), len(file_rpc_get_dishes_proto_rawDesc)))
	})
	return file_rpc_get_dishes_proto_rawDescData
}

var file_rpc_get_dishes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_dishes_proto_goTypes = []any{
	(*GetDishesRequest)(nil),      // 0: pb.GetDishesRequest
	(*GetDishesResponse)(nil),     // 1: pb.GetDishesResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Dish)(nil),                  // 3: pb.Dish
}
var file_rpc_get_dishes_proto_depIdxs = []int32{
	2, // 0: pb.GetDishesRequest.published_at_from:type_name -> google.protobuf.Timestamp
	2, // 1: pb.GetDishesRequest.published_at_to:type_name -> google.protobuf.Timestamp
	3, // 2: pb.GetDishesResponse.dishes:type_name -> pb.Dish
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_get_dishes_proto_init() }
func file_rpc_get_dishes_proto_init() {
	if File_rpc_get_dishes_proto != nil {
		return
	}
	file_dish_proto_init()
	file_rpc_get_dishes_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_dishes_proto_rawDesc), len(file_rpc_get_dishes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_dishes_proto_goTypes,
		DependencyIndexes: file_rpc_get_dishes_proto_depIdxs,
		MessageInfos:      file_rpc_get_dishes_proto_msgTypes,
	}.Build()
	File_rpc_get_dishes_proto = out.File
	file_rpc_get_dishes_proto_goTypes = nil
	file_rpc_get_dishes_proto_depIdxs = nil
}
