// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_posts.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostIds         []int64                `protobuf:"varint,1,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	Search          *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Author          *string                `protobuf:"bytes,3,opt,name=author,proto3,oneof" json:"author,omitempty"`
	PublishedAtFrom *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=published_at_from,json=publishedAtFrom,proto3,oneof" json:"published_at_from,omitempty"`
	PublishedAtTo   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at_to,json=publishedAtTo,proto3,oneof" json:"published_at_to,omitempty"`
	TagId           *int64                 `protobuf:"varint,6,opt,name=tag_id,json=tagId,proto3,oneof" json:"tag_id,omitempty"`
	Category        *int64                 `protobuf:"varint,7,opt,name=category,proto3,oneof" json:"category,omitempty"`
	SortBy          *string                `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortDirection   *string                `protobuf:"bytes,9,opt,name=sort_direction,json=sortDirection,proto3,oneof" json:"sort_direction,omitempty"`
	Limit           *int32                 `protobuf:"varint,10,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset          *int32                 `protobuf:"varint,11,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Status          *string                `protobuf:"bytes,12,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_rpc_get_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_posts_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostsRequest) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *GetPostsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetPostsRequest) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *GetPostsRequest) GetPublishedAtFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAtFrom
	}
	return nil
}

func (x *GetPostsRequest) GetPublishedAtTo() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAtTo
	}
	return nil
}

func (x *GetPostsRequest) GetTagId() int64 {
	if x != nil && x.TagId != nil {
		return *x.TagId
	}
	return 0
}

func (x *GetPostsRequest) GetCategory() int64 {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return 0
}

func (x *GetPostsRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *GetPostsRequest) GetSortDirection() string {
	if x != nil && x.SortDirection != nil {
		return *x.SortDirection
	}
	return ""
}

func (x *GetPostsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetPostsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetPostsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []*Post                `protobuf:"bytes,1,rep,name=post,proto3" json:"post,omitempty"`
	TotalCase     int32                  `protobuf:"varint,2,opt,name=total_case,json=totalCase,proto3" json:"total_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsResponse) Reset() {
	*x = GetPostsResponse{}
	mi := &file_rpc_get_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsResponse) ProtoMessage() {}

func (x *GetPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsResponse.ProtoReflect.Descriptor instead.
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_posts_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostsResponse) GetPost() []*Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetPostsResponse) GetTotalCase() int32 {
	if x != nil {
		return x.TotalCase
	}
	return 0
}

var File_rpc_get_posts_proto protoreflect.FileDescriptor

const file_rpc_get_posts_proto_rawDesc = "" +
	"\n" +
	"\x13rpc_get_posts.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"post.proto\"\xef\x04\n" +
	"\x0fGetPostsRequest\x12\x19\n" +
	"\bpost_ids\x18\x01 \x03(\x03R\apostIds\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x03 \x01(\tH\x01R\x06author\x88\x01\x01\x12K\n" +
	"\x11published_at_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0fpublishedAtFrom\x88\x01\x01\x12G\n" +
	"\x0fpublished_at_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rpublishedAtTo\x88\x01\x01\x12\x1a\n" +
	"\x06tag_id\x18\x06 \x01(\x03H\x04R\x05tagId\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\a \x01(\x03H\x05R\bcategory\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\b \x01(\tH\x06R\x06sortBy\x88\x01\x01\x12*\n" +
	"\x0esort_direction\x18\t \x01(\tH\aR\rsortDirection\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\n" +
	" \x01(\x05H\bR\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\v \x01(\x05H\tR\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\f \x01(\tH\n" +
	"R\x06status\x88\x01\x01B\t\n" +
	"\a_searchB\t\n" +
	"\a_authorB\x14\n" +
	"\x12_published_at_fromB\x12\n" +
	"\x10_published_at_toB\t\n" +
	"\a_tag_idB\v\n" +
	"\t_categoryB\n" +
	"\n" +
	"\b_sort_byB\x11\n" +
	"\x0f_sort_directionB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_status\"O\n" +
	"\x10GetPostsResponse\x12\x1c\n" +
	"\x04post\x18\x01 \x03(\v2\b.pb.PostR\x04post\x12\x1d\n" +
	"\n" +
	"total_case\x18\x02 \x01(\x05R\ttotalCaseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_posts_proto_rawDescOnce sync.Once
	file_rpc_get_posts_proto_rawDescData []byte
)

func file_rpc_get_posts_proto_rawDescGZIP() []byte {
	file_rpc_get_posts_proto_rawDescOnce.Do(func() {
		file_rpc_get_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_posts_proto_rawDesc), len(file_rpc_get_posts_proto_rawDesc)))
	})
	return file_rpc_get_posts_proto_rawDescData
}

var file_rpc_get_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_posts_proto_goTypes = []any{
	(*GetPostsRequest)(nil),       // 0: pb.GetPostsRequest
	(*GetPostsResponse)(nil),      // 1: pb.GetPostsResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Post)(nil),                  // 3: pb.Post
}
var file_rpc_get_posts_proto_depIdxs = []int32{
	2, // 0: pb.GetPostsRequest.published_at_from:type_name -> google.protobuf.Timestamp
	2, // 1: pb.GetPostsRequest.published_at_to:type_name -> google.protobuf.Timestamp
	3, // 2: pb.GetPostsResponse.post:type_name -> pb.Post
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_get_posts_proto_init() }
func file_rpc_get_posts_proto_init() {
	if File_rpc_get_posts_proto != nil {
		return
	}
	file_post_proto_init()
	file_rpc_get_posts_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_posts_proto_rawDesc), len(file_rpc_get_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_posts_proto_goTypes,
		DependencyIndexes: file_rpc_get_posts_proto_depIdxs,
		MessageInfos:      file_rpc_get_posts_proto_msgTypes,
	}.Build()
	File_rpc_get_posts_proto = out.File
	file_rpc_get_posts_proto_goTypes = nil
	file_rpc_get_posts_proto_depIdxs = nil
}
