// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_create_dish.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDishRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price             float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	DiscountRate      float32                `protobuf:"fixed32,3,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	DiscountAmount    float32                `protobuf:"fixed32,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Content           string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Author            string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	ThumbnailUrl      string                 `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	DiscountExpiredAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=discount_expired_at,json=discountExpiredAt,proto3,oneof" json:"discount_expired_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateDishRequest) Reset() {
	*x = CreateDishRequest{}
	mi := &file_rpc_create_dish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDishRequest) ProtoMessage() {}

func (x *CreateDishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_dish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDishRequest.ProtoReflect.Descriptor instead.
func (*CreateDishRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_dish_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDishRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDishRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateDishRequest) GetDiscountRate() float32 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *CreateDishRequest) GetDiscountAmount() float32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CreateDishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDishRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateDishRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CreateDishRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *CreateDishRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateDishRequest) GetDiscountExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscountExpiredAt
	}
	return nil
}

type CreateDishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishId        int64                  `protobuf:"varint,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDishResponse) Reset() {
	*x = CreateDishResponse{}
	mi := &file_rpc_create_dish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDishResponse) ProtoMessage() {}

func (x *CreateDishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_dish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDishResponse.ProtoReflect.Descriptor instead.
func (*CreateDishResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_dish_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDishResponse) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

var File_rpc_create_dish_proto protoreflect.FileDescriptor

const file_rpc_create_dish_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_create_dish.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x03\n" +
	"\x11CreateDishRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12#\n" +
	"\rdiscount_rate\x18\x03 \x01(\x02R\fdiscountRate\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x02R\x0ediscountAmount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12#\n" +
	"\rthumbnail_url\x18\b \x01(\tR\fthumbnailUrl\x12B\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vpublishedAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12O\n" +
	"\x13discount_expired_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x11discountExpiredAt\x88\x01\x01B\x0f\n" +
	"\r_published_atB\x16\n" +
	"\x14_discount_expired_at\"-\n" +
	"\x12CreateDishResponse\x12\x17\n" +
	"\adish_id\x18\x01 \x01(\x03R\x06dishIdB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_create_dish_proto_rawDescOnce sync.Once
	file_rpc_create_dish_proto_rawDescData []byte
)

func file_rpc_create_dish_proto_rawDescGZIP() []byte {
	file_rpc_create_dish_proto_rawDescOnce.Do(func() {
		file_rpc_create_dish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_dish_proto_rawDesc), len(file_rpc_create_dish_proto_rawDesc)))
	})
	return file_rpc_create_dish_proto_rawDescData
}

var file_rpc_create_dish_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_dish_proto_goTypes = []any{
	(*CreateDishRequest)(nil),     // 0: pb.CreateDishRequest
	(*CreateDishResponse)(nil),    // 1: pb.CreateDishResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_rpc_create_dish_proto_depIdxs = []int32{
	2, // 0: pb.CreateDishRequest.published_at:type_name -> google.protobuf.Timestamp
	2, // 1: pb.CreateDishRequest.discount_expired_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_create_dish_proto_init() }
func file_rpc_create_dish_proto_init() {
	if File_rpc_create_dish_proto != nil {
		return
	}
	file_rpc_create_dish_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_dish_proto_rawDesc), len(file_rpc_create_dish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_dish_proto_goTypes,
		DependencyIndexes: file_rpc_create_dish_proto_depIdxs,
		MessageInfos:      file_rpc_create_dish_proto_msgTypes,
	}.Build()
	File_rpc_create_dish_proto = out.File
	file_rpc_create_dish_proto_goTypes = nil
	file_rpc_create_dish_proto_depIdxs = nil
}
