// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_categories.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *string                `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	SortBy        *string                `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortDirection *string                `protobuf:"bytes,3,opt,name=sort_direction,json=sortDirection,proto3,oneof" json:"sort_direction,omitempty"`
	Limit         *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,5,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IsDeleted     *bool                  `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3,oneof" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_rpc_get_categories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_categories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_categories_proto_rawDescGZIP(), []int{0}
}

func (x *GetCategoriesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetCategoriesRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *GetCategoriesRequest) GetSortDirection() string {
	if x != nil && x.SortDirection != nil {
		return *x.SortDirection
	}
	return ""
}

func (x *GetCategoriesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCategoriesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetCategoriesRequest) GetIsDeleted() bool {
	if x != nil && x.IsDeleted != nil {
		return *x.IsDeleted
	}
	return false
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      []*Category            `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_rpc_get_categories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_categories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_categories_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoriesResponse) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_rpc_get_categories_proto protoreflect.FileDescriptor

const file_rpc_get_categories_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_get_categories.proto\x12\x02pb\x1a\x0ecategory.proto\"\xa7\x02\n" +
	"\x14GetCategoriesRequest\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\x02 \x01(\tH\x01R\x06sortBy\x88\x01\x01\x12*\n" +
	"\x0esort_direction\x18\x03 \x01(\tH\x02R\rsortDirection\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x03R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x05 \x01(\x05H\x04R\x06offset\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bH\x05R\tisDeleted\x88\x01\x01B\t\n" +
	"\a_searchB\n" +
	"\n" +
	"\b_sort_byB\x11\n" +
	"\x0f_sort_directionB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\r\n" +
	"\v_is_deleted\"A\n" +
	"\x15GetCategoriesResponse\x12(\n" +
	"\bcategory\x18\x01 \x03(\v2\f.pb.CategoryR\bcategoryB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_categories_proto_rawDescOnce sync.Once
	file_rpc_get_categories_proto_rawDescData []byte
)

func file_rpc_get_categories_proto_rawDescGZIP() []byte {
	file_rpc_get_categories_proto_rawDescOnce.Do(func() {
		file_rpc_get_categories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_categories_proto_rawDesc), len(file_rpc_get_categories_proto_rawDesc)))
	})
	return file_rpc_get_categories_proto_rawDescData
}

var file_rpc_get_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_categories_proto_goTypes = []any{
	(*GetCategoriesRequest)(nil),  // 0: pb.GetCategoriesRequest
	(*GetCategoriesResponse)(nil), // 1: pb.GetCategoriesResponse
	(*Category)(nil),              // 2: pb.Category
}
var file_rpc_get_categories_proto_depIdxs = []int32{
	2, // 0: pb.GetCategoriesResponse.category:type_name -> pb.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_categories_proto_init() }
func file_rpc_get_categories_proto_init() {
	if File_rpc_get_categories_proto != nil {
		return
	}
	file_category_proto_init()
	file_rpc_get_categories_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_categories_proto_rawDesc), len(file_rpc_get_categories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_categories_proto_goTypes,
		DependencyIndexes: file_rpc_get_categories_proto_depIdxs,
		MessageInfos:      file_rpc_get_categories_proto_msgTypes,
	}.Build()
	File_rpc_get_categories_proto = out.File
	file_rpc_get_categories_proto_goTypes = nil
	file_rpc_get_categories_proto_depIdxs = nil
}
