// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_delete_banner.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int64                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBannerRequest) Reset() {
	*x = DeleteBannerRequest{}
	mi := &file_rpc_delete_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerRequest) ProtoMessage() {}

func (x *DeleteBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_banner_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteBannerRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

type DeleteBannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBannerResponse) Reset() {
	*x = DeleteBannerResponse{}
	mi := &file_rpc_delete_banner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerResponse) ProtoMessage() {}

func (x *DeleteBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_banner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerResponse.ProtoReflect.Descriptor instead.
func (*DeleteBannerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_banner_proto_rawDescGZIP(), []int{1}
}

var File_rpc_delete_banner_proto protoreflect.FileDescriptor

const file_rpc_delete_banner_proto_rawDesc = "" +
	"\n" +
	"\x17rpc_delete_banner.proto\x12\x02pb\"2\n" +
	"\x13DeleteBannerRequest\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x03R\bbannerId\"\x16\n" +
	"\x14DeleteBannerResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_delete_banner_proto_rawDescOnce sync.Once
	file_rpc_delete_banner_proto_rawDescData []byte
)

func file_rpc_delete_banner_proto_rawDescGZIP() []byte {
	file_rpc_delete_banner_proto_rawDescOnce.Do(func() {
		file_rpc_delete_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_banner_proto_rawDesc), len(file_rpc_delete_banner_proto_rawDesc)))
	})
	return file_rpc_delete_banner_proto_rawDescData
}

var file_rpc_delete_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_banner_proto_goTypes = []any{
	(*DeleteBannerRequest)(nil),  // 0: pb.DeleteBannerRequest
	(*DeleteBannerResponse)(nil), // 1: pb.DeleteBannerResponse
}
var file_rpc_delete_banner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_banner_proto_init() }
func file_rpc_delete_banner_proto_init() {
	if File_rpc_delete_banner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_banner_proto_rawDesc), len(file_rpc_delete_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_banner_proto_goTypes,
		DependencyIndexes: file_rpc_delete_banner_proto_depIdxs,
		MessageInfos:      file_rpc_delete_banner_proto_msgTypes,
	}.Build()
	File_rpc_delete_banner_proto = out.File
	file_rpc_delete_banner_proto_goTypes = nil
	file_rpc_delete_banner_proto_depIdxs = nil
}
