// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_delete_file.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_rpc_delete_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_file_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFileRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_rpc_delete_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_file_proto_rawDescGZIP(), []int{1}
}

var File_rpc_delete_file_proto protoreflect.FileDescriptor

const file_rpc_delete_file_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_delete_file.proto\x12\x02pb\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\"\x14\n" +
	"\x12DeleteFileResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_delete_file_proto_rawDescOnce sync.Once
	file_rpc_delete_file_proto_rawDescData []byte
)

func file_rpc_delete_file_proto_rawDescGZIP() []byte {
	file_rpc_delete_file_proto_rawDescOnce.Do(func() {
		file_rpc_delete_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_file_proto_rawDesc), len(file_rpc_delete_file_proto_rawDesc)))
	})
	return file_rpc_delete_file_proto_rawDescData
}

var file_rpc_delete_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_file_proto_goTypes = []any{
	(*DeleteFileRequest)(nil),  // 0: pb.DeleteFileRequest
	(*DeleteFileResponse)(nil), // 1: pb.DeleteFileResponse
}
var file_rpc_delete_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_file_proto_init() }
func file_rpc_delete_file_proto_init() {
	if File_rpc_delete_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_file_proto_rawDesc), len(file_rpc_delete_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_file_proto_goTypes,
		DependencyIndexes: file_rpc_delete_file_proto_depIdxs,
		MessageInfos:      file_rpc_delete_file_proto_msgTypes,
	}.Build()
	File_rpc_delete_file_proto = out.File
	file_rpc_delete_file_proto_goTypes = nil
	file_rpc_delete_file_proto_depIdxs = nil
}
