// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_image.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       int64                  `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_rpc_get_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_image_proto_rawDescGZIP(), []int{0}
}

func (x *GetImageRequest) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

type GetImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_rpc_get_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_image_proto_rawDescGZIP(), []int{1}
}

func (x *GetImageResponse) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_rpc_get_image_proto protoreflect.FileDescriptor

const file_rpc_get_image_proto_rawDesc = "" +
	"\n" +
	"\x13rpc_get_image.proto\x12\x02pb\x1a\vimage.proto\",\n" +
	"\x0fGetImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\x03R\aimageId\"3\n" +
	"\x10GetImageResponse\x12\x1f\n" +
	"\x05image\x18\x01 \x01(\v2\t.pb.ImageR\x05imageB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_image_proto_rawDescOnce sync.Once
	file_rpc_get_image_proto_rawDescData []byte
)

func file_rpc_get_image_proto_rawDescGZIP() []byte {
	file_rpc_get_image_proto_rawDescOnce.Do(func() {
		file_rpc_get_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_image_proto_rawDesc), len(file_rpc_get_image_proto_rawDesc)))
	})
	return file_rpc_get_image_proto_rawDescData
}

var file_rpc_get_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_image_proto_goTypes = []any{
	(*GetImageRequest)(nil),  // 0: pb.GetImageRequest
	(*GetImageResponse)(nil), // 1: pb.GetImageResponse
	(*Image)(nil),            // 2: pb.Image
}
var file_rpc_get_image_proto_depIdxs = []int32{
	2, // 0: pb.GetImageResponse.image:type_name -> pb.Image
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_image_proto_init() }
func file_rpc_get_image_proto_init() {
	if File_rpc_get_image_proto != nil {
		return
	}
	file_image_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_image_proto_rawDesc), len(file_rpc_get_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_image_proto_goTypes,
		DependencyIndexes: file_rpc_get_image_proto_depIdxs,
		MessageInfos:      file_rpc_get_image_proto_msgTypes,
	}.Build()
	File_rpc_get_image_proto = out.File
	file_rpc_get_image_proto_goTypes = nil
	file_rpc_get_image_proto_depIdxs = nil
}
