// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_update_post.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	ThumbnailUrl  *string                `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	Status        *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	PostId        int64                  `protobuf:"varint,7,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_rpc_update_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_post_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdatePostRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *UpdatePostRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *UpdatePostRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdatePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_rpc_update_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_post_proto_rawDescGZIP(), []int{1}
}

var File_rpc_update_post_proto protoreflect.FileDescriptor

const file_rpc_update_post_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_update_post.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x02\n" +
	"\x11UpdatePostRequest\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x02R\acontent\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\x04 \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x12B\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vpublishedAt\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x05R\x06status\x88\x01\x01\x12\x17\n" +
	"\apost_id\x18\a \x01(\x03R\x06postIdB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_contentB\x10\n" +
	"\x0e_thumbnail_urlB\x0f\n" +
	"\r_published_atB\t\n" +
	"\a_status\"\x14\n" +
	"\x12UpdatePostResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_update_post_proto_rawDescOnce sync.Once
	file_rpc_update_post_proto_rawDescData []byte
)

func file_rpc_update_post_proto_rawDescGZIP() []byte {
	file_rpc_update_post_proto_rawDescOnce.Do(func() {
		file_rpc_update_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_post_proto_rawDesc), len(file_rpc_update_post_proto_rawDesc)))
	})
	return file_rpc_update_post_proto_rawDescData
}

var file_rpc_update_post_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_post_proto_goTypes = []any{
	(*UpdatePostRequest)(nil),     // 0: pb.UpdatePostRequest
	(*UpdatePostResponse)(nil),    // 1: pb.UpdatePostResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_rpc_update_post_proto_depIdxs = []int32{
	2, // 0: pb.UpdatePostRequest.published_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_post_proto_init() }
func file_rpc_update_post_proto_init() {
	if File_rpc_update_post_proto != nil {
		return
	}
	file_rpc_update_post_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_post_proto_rawDesc), len(file_rpc_update_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_post_proto_goTypes,
		DependencyIndexes: file_rpc_update_post_proto_depIdxs,
		MessageInfos:      file_rpc_update_post_proto_msgTypes,
	}.Build()
	File_rpc_update_post_proto = out.File
	file_rpc_update_post_proto_goTypes = nil
	file_rpc_update_post_proto_depIdxs = nil
}
