// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_upload_file.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_rpc_upload_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_upload_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_upload_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UploadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_rpc_upload_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_upload_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_upload_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_rpc_upload_file_proto protoreflect.FileDescriptor

const file_rpc_upload_file_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_upload_file.proto\x12\x02pb\";\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x12UploadFileResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04linkB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_upload_file_proto_rawDescOnce sync.Once
	file_rpc_upload_file_proto_rawDescData []byte
)

func file_rpc_upload_file_proto_rawDescGZIP() []byte {
	file_rpc_upload_file_proto_rawDescOnce.Do(func() {
		file_rpc_upload_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_upload_file_proto_rawDesc), len(file_rpc_upload_file_proto_rawDesc)))
	})
	return file_rpc_upload_file_proto_rawDescData
}

var file_rpc_upload_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_upload_file_proto_goTypes = []any{
	(*UploadFileRequest)(nil),  // 0: pb.UploadFileRequest
	(*UploadFileResponse)(nil), // 1: pb.UploadFileResponse
}
var file_rpc_upload_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_upload_file_proto_init() }
func file_rpc_upload_file_proto_init() {
	if File_rpc_upload_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_upload_file_proto_rawDesc), len(file_rpc_upload_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_upload_file_proto_goTypes,
		DependencyIndexes: file_rpc_upload_file_proto_depIdxs,
		MessageInfos:      file_rpc_upload_file_proto_msgTypes,
	}.Build()
	File_rpc_upload_file_proto = out.File
	file_rpc_upload_file_proto_goTypes = nil
	file_rpc_upload_file_proto_depIdxs = nil
}
