// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_upload_images.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_rpc_upload_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_upload_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_upload_images_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UploadImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadImageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_rpc_upload_images_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_upload_images_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_upload_images_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_rpc_upload_images_proto protoreflect.FileDescriptor

const file_rpc_upload_images_proto_rawDesc = "" +
	"\n" +
	"\x17rpc_upload_images.proto\x12\x02pb\"P\n" +
	"\x12UploadImageRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\")\n" +
	"\x13UploadImageResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04linkB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_upload_images_proto_rawDescOnce sync.Once
	file_rpc_upload_images_proto_rawDescData []byte
)

func file_rpc_upload_images_proto_rawDescGZIP() []byte {
	file_rpc_upload_images_proto_rawDescOnce.Do(func() {
		file_rpc_upload_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_upload_images_proto_rawDesc), len(file_rpc_upload_images_proto_rawDesc)))
	})
	return file_rpc_upload_images_proto_rawDescData
}

var file_rpc_upload_images_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_upload_images_proto_goTypes = []any{
	(*UploadImageRequest)(nil),  // 0: pb.UploadImageRequest
	(*UploadImageResponse)(nil), // 1: pb.UploadImageResponse
}
var file_rpc_upload_images_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_upload_images_proto_init() }
func file_rpc_upload_images_proto_init() {
	if File_rpc_upload_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_upload_images_proto_rawDesc), len(file_rpc_upload_images_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_upload_images_proto_goTypes,
		DependencyIndexes: file_rpc_upload_images_proto_depIdxs,
		MessageInfos:      file_rpc_upload_images_proto_msgTypes,
	}.Build()
	File_rpc_upload_images_proto = out.File
	file_rpc_upload_images_proto_goTypes = nil
	file_rpc_upload_images_proto_depIdxs = nil
}
