// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_update_dish.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDishRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Price             *int32                 `protobuf:"varint,2,opt,name=price,proto3,oneof" json:"price,omitempty"`
	DiscountRate      *float32               `protobuf:"fixed32,3,opt,name=discount_rate,json=discountRate,proto3,oneof" json:"discount_rate,omitempty"`
	DiscountAmount    *int32                 `protobuf:"varint,4,opt,name=discount_amount,json=discountAmount,proto3,oneof" json:"discount_amount,omitempty"`
	Description       *string                `protobuf:"bytes,55,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Content           *string                `protobuf:"bytes,6,opt,name=content,proto3,oneof" json:"content,omitempty"`
	ThumbnailUrl      *string                `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	Status            *string                `protobuf:"bytes,9,opt,name=status,proto3,oneof" json:"status,omitempty"`
	DishId            int64                  `protobuf:"varint,10,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	DiscountExpiredAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=discount_expired_at,json=discountExpiredAt,proto3,oneof" json:"discount_expired_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDishRequest) Reset() {
	*x = UpdateDishRequest{}
	mi := &file_rpc_update_dish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishRequest) ProtoMessage() {}

func (x *UpdateDishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_dish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishRequest.ProtoReflect.Descriptor instead.
func (*UpdateDishRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_dish_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDishRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateDishRequest) GetPrice() int32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateDishRequest) GetDiscountRate() float32 {
	if x != nil && x.DiscountRate != nil {
		return *x.DiscountRate
	}
	return 0
}

func (x *UpdateDishRequest) GetDiscountAmount() int32 {
	if x != nil && x.DiscountAmount != nil {
		return *x.DiscountAmount
	}
	return 0
}

func (x *UpdateDishRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateDishRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateDishRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *UpdateDishRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *UpdateDishRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateDishRequest) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *UpdateDishRequest) GetDiscountExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscountExpiredAt
	}
	return nil
}

type UpdateDishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDishResponse) Reset() {
	*x = UpdateDishResponse{}
	mi := &file_rpc_update_dish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishResponse) ProtoMessage() {}

func (x *UpdateDishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_dish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishResponse.ProtoReflect.Descriptor instead.
func (*UpdateDishResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_dish_proto_rawDescGZIP(), []int{1}
}

var File_rpc_update_dish_proto protoreflect.FileDescriptor

const file_rpc_update_dish_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_update_dish.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x04\n" +
	"\x11UpdateDishRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x02 \x01(\x05H\x01R\x05price\x88\x01\x01\x12(\n" +
	"\rdiscount_rate\x18\x03 \x01(\x02H\x02R\fdiscountRate\x88\x01\x01\x12,\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x05H\x03R\x0ediscountAmount\x88\x01\x01\x12%\n" +
	"\vdescription\x187 \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x06 \x01(\tH\x05R\acontent\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\a \x01(\tH\x06R\fthumbnailUrl\x88\x01\x01\x12B\n" +
	"\fpublished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\aR\vpublishedAt\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\t \x01(\tH\bR\x06status\x88\x01\x01\x12\x17\n" +
	"\adish_id\x18\n" +
	" \x01(\x03R\x06dishId\x12O\n" +
	"\x13discount_expired_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\tR\x11discountExpiredAt\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_priceB\x10\n" +
	"\x0e_discount_rateB\x12\n" +
	"\x10_discount_amountB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_contentB\x10\n" +
	"\x0e_thumbnail_urlB\x0f\n" +
	"\r_published_atB\t\n" +
	"\a_statusB\x16\n" +
	"\x14_discount_expired_at\"\x14\n" +
	"\x12UpdateDishResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_update_dish_proto_rawDescOnce sync.Once
	file_rpc_update_dish_proto_rawDescData []byte
)

func file_rpc_update_dish_proto_rawDescGZIP() []byte {
	file_rpc_update_dish_proto_rawDescOnce.Do(func() {
		file_rpc_update_dish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_dish_proto_rawDesc), len(file_rpc_update_dish_proto_rawDesc)))
	})
	return file_rpc_update_dish_proto_rawDescData
}

var file_rpc_update_dish_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_dish_proto_goTypes = []any{
	(*UpdateDishRequest)(nil),     // 0: pb.UpdateDishRequest
	(*UpdateDishResponse)(nil),    // 1: pb.UpdateDishResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_rpc_update_dish_proto_depIdxs = []int32{
	2, // 0: pb.UpdateDishRequest.published_at:type_name -> google.protobuf.Timestamp
	2, // 1: pb.UpdateDishRequest.discount_expired_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_update_dish_proto_init() }
func file_rpc_update_dish_proto_init() {
	if File_rpc_update_dish_proto != nil {
		return
	}
	file_rpc_update_dish_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_dish_proto_rawDesc), len(file_rpc_update_dish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_dish_proto_goTypes,
		DependencyIndexes: file_rpc_update_dish_proto_depIdxs,
		MessageInfos:      file_rpc_update_dish_proto_msgTypes,
	}.Build()
	File_rpc_update_dish_proto = out.File
	file_rpc_update_dish_proto_goTypes = nil
	file_rpc_update_dish_proto_depIdxs = nil
}
