// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_images.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesRequest) Reset() {
	*x = GetImagesRequest{}
	mi := &file_rpc_get_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesRequest) ProtoMessage() {}

func (x *GetImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesRequest.ProtoReflect.Descriptor instead.
func (*GetImagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_images_proto_rawDescGZIP(), []int{0}
}

func (x *GetImagesRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetImagesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetImagesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetImagesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	TotalCase     int32                  `protobuf:"varint,2,opt,name=total_case,json=totalCase,proto3" json:"total_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesResponse) Reset() {
	*x = GetImagesResponse{}
	mi := &file_rpc_get_images_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesResponse) ProtoMessage() {}

func (x *GetImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_images_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesResponse.ProtoReflect.Descriptor instead.
func (*GetImagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_images_proto_rawDescGZIP(), []int{1}
}

func (x *GetImagesResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GetImagesResponse) GetTotalCase() int32 {
	if x != nil {
		return x.TotalCase
	}
	return 0
}

var File_rpc_get_images_proto protoreflect.FileDescriptor

const file_rpc_get_images_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_get_images.proto\x12\x02pb\x1a\vimage.proto\"\xa3\x01\n" +
	"\x10GetImagesRequest\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x05H\x03R\x06offset\x88\x01\x01B\a\n" +
	"\x05_typeB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"U\n" +
	"\x11GetImagesResponse\x12!\n" +
	"\x06images\x18\x01 \x03(\v2\t.pb.ImageR\x06images\x12\x1d\n" +
	"\n" +
	"total_case\x18\x02 \x01(\x05R\ttotalCaseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_images_proto_rawDescOnce sync.Once
	file_rpc_get_images_proto_rawDescData []byte
)

func file_rpc_get_images_proto_rawDescGZIP() []byte {
	file_rpc_get_images_proto_rawDescOnce.Do(func() {
		file_rpc_get_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_images_proto_rawDesc), len(file_rpc_get_images_proto_rawDesc)))
	})
	return file_rpc_get_images_proto_rawDescData
}

var file_rpc_get_images_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_images_proto_goTypes = []any{
	(*GetImagesRequest)(nil),  // 0: pb.GetImagesRequest
	(*GetImagesResponse)(nil), // 1: pb.GetImagesResponse
	(*Image)(nil),             // 2: pb.Image
}
var file_rpc_get_images_proto_depIdxs = []int32{
	2, // 0: pb.GetImagesResponse.images:type_name -> pb.Image
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_images_proto_init() }
func file_rpc_get_images_proto_init() {
	if File_rpc_get_images_proto != nil {
		return
	}
	file_image_proto_init()
	file_rpc_get_images_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_images_proto_rawDesc), len(file_rpc_get_images_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_images_proto_goTypes,
		DependencyIndexes: file_rpc_get_images_proto_depIdxs,
		MessageInfos:      file_rpc_get_images_proto_msgTypes,
	}.Build()
	File_rpc_get_images_proto = out.File
	file_rpc_get_images_proto_goTypes = nil
	file_rpc_get_images_proto_depIdxs = nil
}
