// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_files.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesRequest) Reset() {
	*x = GetFilesRequest{}
	mi := &file_rpc_get_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesRequest) ProtoMessage() {}

func (x *GetFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesRequest.ProtoReflect.Descriptor instead.
func (*GetFilesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_files_proto_rawDescGZIP(), []int{0}
}

func (x *GetFilesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetFilesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetFilesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TotalCase     int32                  `protobuf:"varint,2,opt,name=total_case,json=totalCase,proto3" json:"total_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesResponse) Reset() {
	*x = GetFilesResponse{}
	mi := &file_rpc_get_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesResponse) ProtoMessage() {}

func (x *GetFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesResponse.ProtoReflect.Descriptor instead.
func (*GetFilesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_files_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetFilesResponse) GetTotalCase() int32 {
	if x != nil {
		return x.TotalCase
	}
	return 0
}

var File_rpc_get_files_proto protoreflect.FileDescriptor

const file_rpc_get_files_proto_rawDesc = "" +
	"\n" +
	"\x13rpc_get_files.proto\x12\x02pb\x1a\n" +
	"file.proto\"\x80\x01\n" +
	"\x0fGetFilesRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x02R\x06offset\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"Q\n" +
	"\x10GetFilesResponse\x12\x1e\n" +
	"\x05files\x18\x01 \x03(\v2\b.pb.FileR\x05files\x12\x1d\n" +
	"\n" +
	"total_case\x18\x02 \x01(\x05R\ttotalCaseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_files_proto_rawDescOnce sync.Once
	file_rpc_get_files_proto_rawDescData []byte
)

func file_rpc_get_files_proto_rawDescGZIP() []byte {
	file_rpc_get_files_proto_rawDescOnce.Do(func() {
		file_rpc_get_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_files_proto_rawDesc), len(file_rpc_get_files_proto_rawDesc)))
	})
	return file_rpc_get_files_proto_rawDescData
}

var file_rpc_get_files_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_files_proto_goTypes = []any{
	(*GetFilesRequest)(nil),  // 0: pb.GetFilesRequest
	(*GetFilesResponse)(nil), // 1: pb.GetFilesResponse
	(*File)(nil),             // 2: pb.File
}
var file_rpc_get_files_proto_depIdxs = []int32{
	2, // 0: pb.GetFilesResponse.files:type_name -> pb.File
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_files_proto_init() }
func file_rpc_get_files_proto_init() {
	if File_rpc_get_files_proto != nil {
		return
	}
	file_file_proto_init()
	file_rpc_get_files_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_files_proto_rawDesc), len(file_rpc_get_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_files_proto_goTypes,
		DependencyIndexes: file_rpc_get_files_proto_depIdxs,
		MessageInfos:      file_rpc_get_files_proto_msgTypes,
	}.Build()
	File_rpc_get_files_proto = out.File
	file_rpc_get_files_proto_goTypes = nil
	file_rpc_get_files_proto_depIdxs = nil
}
