// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: operator_service.proto

package source_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperatorService_RPCCreateAdmin_FullMethodName                = "/pb.OperatorService/RPCCreateAdmin"
	OperatorService_RPCCreateOperator_FullMethodName             = "/pb.OperatorService/RPCCreateOperator"
	OperatorService_RPCVerifyOperator_FullMethodName             = "/pb.OperatorService/RPCVerifyOperator"
	OperatorService_RPCGetOperator_FullMethodName                = "/pb.OperatorService/RPCGetOperator"
	OperatorService_RPCGetOperatorList_FullMethodName            = "/pb.OperatorService/RPCGetOperatorList"
	OperatorService_RPCUpdateOperator_FullMethodName             = "/pb.OperatorService/RPCUpdateOperator"
	OperatorService_RPCResendOperatorVerification_FullMethodName = "/pb.OperatorService/RPCResendOperatorVerification"
	OperatorService_RPCCheckAdminExisting_FullMethodName         = "/pb.OperatorService/RPCCheckAdminExisting"
)

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperatorServiceClient interface {
	// op000001
	RPCCreateAdmin(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*CreateOperatorResponse, error)
	// op000002
	RPCCreateOperator(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*CreateOperatorResponse, error)
	// op000003
	RPCVerifyOperator(ctx context.Context, in *VerifyOperatorRequest, opts ...grpc.CallOption) (*VerifyOperatorResponse, error)
	// op000004
	RPCGetOperator(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*GetOperatorResponse, error)
	// op000005
	RPCGetOperatorList(ctx context.Context, in *GetOperatorListRequest, opts ...grpc.CallOption) (*GetOperatorListResponse, error)
	// op000006
	RPCUpdateOperator(ctx context.Context, in *UpdateOperatorRequest, opts ...grpc.CallOption) (*UpdateOperatorResponse, error)
	// op000007
	RPCResendOperatorVerification(ctx context.Context, in *ResendOperatorVerificationRequest, opts ...grpc.CallOption) (*ResendOperatorVerificationResponse, error)
	// op000008
	RPCCheckAdminExisting(ctx context.Context, in *CheckAdminExistingRequest, opts ...grpc.CallOption) (*CheckAdminExistingResponse, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) RPCCreateAdmin(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*CreateOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCCreateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCCreateOperator(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*CreateOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCCreateOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCVerifyOperator(ctx context.Context, in *VerifyOperatorRequest, opts ...grpc.CallOption) (*VerifyOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCVerifyOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCGetOperator(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*GetOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCGetOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCGetOperatorList(ctx context.Context, in *GetOperatorListRequest, opts ...grpc.CallOption) (*GetOperatorListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperatorListResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCGetOperatorList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCUpdateOperator(ctx context.Context, in *UpdateOperatorRequest, opts ...grpc.CallOption) (*UpdateOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCUpdateOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCResendOperatorVerification(ctx context.Context, in *ResendOperatorVerificationRequest, opts ...grpc.CallOption) (*ResendOperatorVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendOperatorVerificationResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCResendOperatorVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RPCCheckAdminExisting(ctx context.Context, in *CheckAdminExistingRequest, opts ...grpc.CallOption) (*CheckAdminExistingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAdminExistingResponse)
	err := c.cc.Invoke(ctx, OperatorService_RPCCheckAdminExisting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServiceServer is the server API for OperatorService service.
// All implementations must embed UnimplementedOperatorServiceServer
// for forward compatibility.
type OperatorServiceServer interface {
	// op000001
	RPCCreateAdmin(context.Context, *CreateOperatorRequest) (*CreateOperatorResponse, error)
	// op000002
	RPCCreateOperator(context.Context, *CreateOperatorRequest) (*CreateOperatorResponse, error)
	// op000003
	RPCVerifyOperator(context.Context, *VerifyOperatorRequest) (*VerifyOperatorResponse, error)
	// op000004
	RPCGetOperator(context.Context, *GetOperatorRequest) (*GetOperatorResponse, error)
	// op000005
	RPCGetOperatorList(context.Context, *GetOperatorListRequest) (*GetOperatorListResponse, error)
	// op000006
	RPCUpdateOperator(context.Context, *UpdateOperatorRequest) (*UpdateOperatorResponse, error)
	// op000007
	RPCResendOperatorVerification(context.Context, *ResendOperatorVerificationRequest) (*ResendOperatorVerificationResponse, error)
	// op000008
	RPCCheckAdminExisting(context.Context, *CheckAdminExistingRequest) (*CheckAdminExistingResponse, error)
	mustEmbedUnimplementedOperatorServiceServer()
}

// UnimplementedOperatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorServiceServer struct{}

func (UnimplementedOperatorServiceServer) RPCCreateAdmin(context.Context, *CreateOperatorRequest) (*CreateOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCCreateAdmin not implemented")
}
func (UnimplementedOperatorServiceServer) RPCCreateOperator(context.Context, *CreateOperatorRequest) (*CreateOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCCreateOperator not implemented")
}
func (UnimplementedOperatorServiceServer) RPCVerifyOperator(context.Context, *VerifyOperatorRequest) (*VerifyOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCVerifyOperator not implemented")
}
func (UnimplementedOperatorServiceServer) RPCGetOperator(context.Context, *GetOperatorRequest) (*GetOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCGetOperator not implemented")
}
func (UnimplementedOperatorServiceServer) RPCGetOperatorList(context.Context, *GetOperatorListRequest) (*GetOperatorListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCGetOperatorList not implemented")
}
func (UnimplementedOperatorServiceServer) RPCUpdateOperator(context.Context, *UpdateOperatorRequest) (*UpdateOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCUpdateOperator not implemented")
}
func (UnimplementedOperatorServiceServer) RPCResendOperatorVerification(context.Context, *ResendOperatorVerificationRequest) (*ResendOperatorVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCResendOperatorVerification not implemented")
}
func (UnimplementedOperatorServiceServer) RPCCheckAdminExisting(context.Context, *CheckAdminExistingRequest) (*CheckAdminExistingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCCheckAdminExisting not implemented")
}
func (UnimplementedOperatorServiceServer) mustEmbedUnimplementedOperatorServiceServer() {}
func (UnimplementedOperatorServiceServer) testEmbeddedByValue()                         {}

// UnsafeOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServiceServer will
// result in compilation errors.
type UnsafeOperatorServiceServer interface {
	mustEmbedUnimplementedOperatorServiceServer()
}

func RegisterOperatorServiceServer(s grpc.ServiceRegistrar, srv OperatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedOperatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorService_ServiceDesc, srv)
}

func _OperatorService_RPCCreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCCreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCCreateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCCreateAdmin(ctx, req.(*CreateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCCreateOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCCreateOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCCreateOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCCreateOperator(ctx, req.(*CreateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCVerifyOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCVerifyOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCVerifyOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCVerifyOperator(ctx, req.(*VerifyOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCGetOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCGetOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCGetOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCGetOperator(ctx, req.(*GetOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCGetOperatorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCGetOperatorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCGetOperatorList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCGetOperatorList(ctx, req.(*GetOperatorListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCUpdateOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCUpdateOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCUpdateOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCUpdateOperator(ctx, req.(*UpdateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCResendOperatorVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendOperatorVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCResendOperatorVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCResendOperatorVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCResendOperatorVerification(ctx, req.(*ResendOperatorVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RPCCheckAdminExisting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAdminExistingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RPCCheckAdminExisting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RPCCheckAdminExisting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RPCCheckAdminExisting(ctx, req.(*CheckAdminExistingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorService_ServiceDesc is the grpc.ServiceDesc for OperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RPCCreateAdmin",
			Handler:    _OperatorService_RPCCreateAdmin_Handler,
		},
		{
			MethodName: "RPCCreateOperator",
			Handler:    _OperatorService_RPCCreateOperator_Handler,
		},
		{
			MethodName: "RPCVerifyOperator",
			Handler:    _OperatorService_RPCVerifyOperator_Handler,
		},
		{
			MethodName: "RPCGetOperator",
			Handler:    _OperatorService_RPCGetOperator_Handler,
		},
		{
			MethodName: "RPCGetOperatorList",
			Handler:    _OperatorService_RPCGetOperatorList_Handler,
		},
		{
			MethodName: "RPCUpdateOperator",
			Handler:    _OperatorService_RPCUpdateOperator_Handler,
		},
		{
			MethodName: "RPCResendOperatorVerification",
			Handler:    _OperatorService_RPCResendOperatorVerification_Handler,
		},
		{
			MethodName: "RPCCheckAdminExisting",
			Handler:    _OperatorService_RPCCheckAdminExisting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator_service.proto",
}
