// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_operator_health_check.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorHealthCheckRequest) Reset() {
	*x = OperatorHealthCheckRequest{}
	mi := &file_rpc_operator_health_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorHealthCheckRequest) ProtoMessage() {}

func (x *OperatorHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_operator_health_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*OperatorHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_operator_health_check_proto_rawDescGZIP(), []int{0}
}

type OperatorHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorHealthCheckResponse) Reset() {
	*x = OperatorHealthCheckResponse{}
	mi := &file_rpc_operator_health_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorHealthCheckResponse) ProtoMessage() {}

func (x *OperatorHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_operator_health_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*OperatorHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_operator_health_check_proto_rawDescGZIP(), []int{1}
}

var File_rpc_operator_health_check_proto protoreflect.FileDescriptor

const file_rpc_operator_health_check_proto_rawDesc = "" +
	"\n" +
	"\x1frpc_operator_health_check.proto\x12\x02pb\"\x1c\n" +
	"\x1aOperatorHealthCheckRequest\"\x1d\n" +
	"\x1bOperatorHealthCheckResponseB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_operator_health_check_proto_rawDescOnce sync.Once
	file_rpc_operator_health_check_proto_rawDescData []byte
)

func file_rpc_operator_health_check_proto_rawDescGZIP() []byte {
	file_rpc_operator_health_check_proto_rawDescOnce.Do(func() {
		file_rpc_operator_health_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_operator_health_check_proto_rawDesc), len(file_rpc_operator_health_check_proto_rawDesc)))
	})
	return file_rpc_operator_health_check_proto_rawDescData
}

var file_rpc_operator_health_check_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_operator_health_check_proto_goTypes = []any{
	(*OperatorHealthCheckRequest)(nil),  // 0: pb.OperatorHealthCheckRequest
	(*OperatorHealthCheckResponse)(nil), // 1: pb.OperatorHealthCheckResponse
}
var file_rpc_operator_health_check_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_operator_health_check_proto_init() }
func file_rpc_operator_health_check_proto_init() {
	if File_rpc_operator_health_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_operator_health_check_proto_rawDesc), len(file_rpc_operator_health_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_operator_health_check_proto_goTypes,
		DependencyIndexes: file_rpc_operator_health_check_proto_depIdxs,
		MessageInfos:      file_rpc_operator_health_check_proto_msgTypes,
	}.Build()
	File_rpc_operator_health_check_proto = out.File
	file_rpc_operator_health_check_proto_goTypes = nil
	file_rpc_operator_health_check_proto_depIdxs = nil
}
