// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_create_operator.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOperatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Role          *CreateRoleRequest     `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatorRequest) Reset() {
	*x = CreateOperatorRequest{}
	mi := &file_rpc_create_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatorRequest) ProtoMessage() {}

func (x *CreateOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatorRequest.ProtoReflect.Descriptor instead.
func (*CreateOperatorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_operator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOperatorRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateOperatorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateOperatorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOperatorRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateOperatorRequest) GetRole() *CreateRoleRequest {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *CreateOperatorRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *int32                 `protobuf:"varint,1,opt,name=admin,proto3,oneof" json:"admin,omitempty"`
	Operator      *int32                 `protobuf:"varint,2,opt,name=operator,proto3,oneof" json:"operator,omitempty"`
	Post          *int32                 `protobuf:"varint,3,opt,name=post,proto3,oneof" json:"post,omitempty"`
	Notification  *int32                 `protobuf:"varint,4,opt,name=notification,proto3,oneof" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_rpc_create_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_operator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRequest) GetAdmin() int32 {
	if x != nil && x.Admin != nil {
		return *x.Admin
	}
	return 0
}

func (x *CreateRoleRequest) GetOperator() int32 {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return 0
}

func (x *CreateRoleRequest) GetPost() int32 {
	if x != nil && x.Post != nil {
		return *x.Post
	}
	return 0
}

func (x *CreateRoleRequest) GetNotification() int32 {
	if x != nil && x.Notification != nil {
		return *x.Notification
	}
	return 0
}

type CreateOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *Operator              `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SecretCode    string                 `protobuf:"bytes,3,opt,name=secret_code,json=secretCode,proto3" json:"secret_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatorResponse) Reset() {
	*x = CreateOperatorResponse{}
	mi := &file_rpc_create_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatorResponse) ProtoMessage() {}

func (x *CreateOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatorResponse.ProtoReflect.Descriptor instead.
func (*CreateOperatorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_operator_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOperatorResponse) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *CreateOperatorResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateOperatorResponse) GetSecretCode() string {
	if x != nil {
		return x.SecretCode
	}
	return ""
}

var File_rpc_create_operator_proto protoreflect.FileDescriptor

const file_rpc_create_operator_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_create_operator.proto\x12\x02pb\x1a\x0eoperator.proto\"\xd0\x01\n" +
	"\x15CreateOperatorRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12)\n" +
	"\x04role\x18\x05 \x01(\v2\x15.pb.CreateRoleRequestR\x04role\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\xc2\x01\n" +
	"\x11CreateRoleRequest\x12\x19\n" +
	"\x05admin\x18\x01 \x01(\x05H\x00R\x05admin\x88\x01\x01\x12\x1f\n" +
	"\boperator\x18\x02 \x01(\x05H\x01R\boperator\x88\x01\x01\x12\x17\n" +
	"\x04post\x18\x03 \x01(\x05H\x02R\x04post\x88\x01\x01\x12'\n" +
	"\fnotification\x18\x04 \x01(\x05H\x03R\fnotification\x88\x01\x01B\b\n" +
	"\x06_adminB\v\n" +
	"\t_operatorB\a\n" +
	"\x05_postB\x0f\n" +
	"\r_notification\"\x7f\n" +
	"\x16CreateOperatorResponse\x12(\n" +
	"\boperator\x18\x01 \x01(\v2\f.pb.OperatorR\boperator\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vsecret_code\x18\x03 \x01(\tR\n" +
	"secretCodeB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_create_operator_proto_rawDescOnce sync.Once
	file_rpc_create_operator_proto_rawDescData []byte
)

func file_rpc_create_operator_proto_rawDescGZIP() []byte {
	file_rpc_create_operator_proto_rawDescOnce.Do(func() {
		file_rpc_create_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_operator_proto_rawDesc), len(file_rpc_create_operator_proto_rawDesc)))
	})
	return file_rpc_create_operator_proto_rawDescData
}

var file_rpc_create_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_create_operator_proto_goTypes = []any{
	(*CreateOperatorRequest)(nil),  // 0: pb.CreateOperatorRequest
	(*CreateRoleRequest)(nil),      // 1: pb.CreateRoleRequest
	(*CreateOperatorResponse)(nil), // 2: pb.CreateOperatorResponse
	(*Operator)(nil),               // 3: pb.Operator
}
var file_rpc_create_operator_proto_depIdxs = []int32{
	1, // 0: pb.CreateOperatorRequest.role:type_name -> pb.CreateRoleRequest
	3, // 1: pb.CreateOperatorResponse.operator:type_name -> pb.Operator
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_create_operator_proto_init() }
func file_rpc_create_operator_proto_init() {
	if File_rpc_create_operator_proto != nil {
		return
	}
	file_operator_proto_init()
	file_rpc_create_operator_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_operator_proto_rawDesc), len(file_rpc_create_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_operator_proto_goTypes,
		DependencyIndexes: file_rpc_create_operator_proto_depIdxs,
		MessageInfos:      file_rpc_create_operator_proto_msgTypes,
	}.Build()
	File_rpc_create_operator_proto = out.File
	file_rpc_create_operator_proto_goTypes = nil
	file_rpc_create_operator_proto_depIdxs = nil
}
