// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc_get_operator_list.proto

package source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOperatorListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    *int64                 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	Search        *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorListRequest) Reset() {
	*x = GetOperatorListRequest{}
	mi := &file_rpc_get_operator_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorListRequest) ProtoMessage() {}

func (x *GetOperatorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_operator_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorListRequest.ProtoReflect.Descriptor instead.
func (*GetOperatorListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_operator_list_proto_rawDescGZIP(), []int{0}
}

func (x *GetOperatorListRequest) GetOperatorId() int64 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *GetOperatorListRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetOperatorListRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetOperatorListRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

type GetOperatorListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      []*OperatorList        `protobuf:"bytes,1,rep,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorListResponse) Reset() {
	*x = GetOperatorListResponse{}
	mi := &file_rpc_get_operator_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorListResponse) ProtoMessage() {}

func (x *GetOperatorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_operator_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorListResponse.ProtoReflect.Descriptor instead.
func (*GetOperatorListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_operator_list_proto_rawDescGZIP(), []int{1}
}

func (x *GetOperatorListResponse) GetOperator() []*OperatorList {
	if x != nil {
		return x.Operator
	}
	return nil
}

var File_rpc_get_operator_list_proto protoreflect.FileDescriptor

const file_rpc_get_operator_list_proto_rawDesc = "" +
	"\n" +
	"\x1brpc_get_operator_list.proto\x12\x02pb\x1a\x0eoperator.proto\"\xd7\x01\n" +
	"\x16GetOperatorListRequest\x12$\n" +
	"\voperator_id\x18\x01 \x01(\x03H\x00R\n" +
	"operatorId\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x01R\x06search\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\x04 \x01(\tH\x03R\vphoneNumber\x88\x01\x01B\x0e\n" +
	"\f_operator_idB\t\n" +
	"\a_searchB\t\n" +
	"\a_statusB\x0f\n" +
	"\r_phone_number\"G\n" +
	"\x17GetOperatorListResponse\x12,\n" +
	"\boperator\x18\x01 \x03(\v2\x10.pb.OperatorListR\boperatorB(Z&github.com/dinhtatuanlinh/source_protob\x06proto3"

var (
	file_rpc_get_operator_list_proto_rawDescOnce sync.Once
	file_rpc_get_operator_list_proto_rawDescData []byte
)

func file_rpc_get_operator_list_proto_rawDescGZIP() []byte {
	file_rpc_get_operator_list_proto_rawDescOnce.Do(func() {
		file_rpc_get_operator_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_operator_list_proto_rawDesc), len(file_rpc_get_operator_list_proto_rawDesc)))
	})
	return file_rpc_get_operator_list_proto_rawDescData
}

var file_rpc_get_operator_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_operator_list_proto_goTypes = []any{
	(*GetOperatorListRequest)(nil),  // 0: pb.GetOperatorListRequest
	(*GetOperatorListResponse)(nil), // 1: pb.GetOperatorListResponse
	(*OperatorList)(nil),            // 2: pb.OperatorList
}
var file_rpc_get_operator_list_proto_depIdxs = []int32{
	2, // 0: pb.GetOperatorListResponse.operator:type_name -> pb.OperatorList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_operator_list_proto_init() }
func file_rpc_get_operator_list_proto_init() {
	if File_rpc_get_operator_list_proto != nil {
		return
	}
	file_operator_proto_init()
	file_rpc_get_operator_list_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_operator_list_proto_rawDesc), len(file_rpc_get_operator_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_operator_list_proto_goTypes,
		DependencyIndexes: file_rpc_get_operator_list_proto_depIdxs,
		MessageInfos:      file_rpc_get_operator_list_proto_msgTypes,
	}.Build()
	File_rpc_get_operator_list_proto = out.File
	file_rpc_get_operator_list_proto_goTypes = nil
	file_rpc_get_operator_list_proto_depIdxs = nil
}
